version: '2'
services:
  web:
    image: httpd:2.4
    ports:
      - "80:80"
    links:
      - fluentd
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: httpd.access

  fluentd:
    build: ./fluentd
    volumes:
      - ./fluentd/conf:/fluentd/etc
    links:
      - "elasticsearch"
    ports:
      - "24224:24224"
      - "24224:24224/udp"

  elasticsearch:
    image: elasticsearch:6.8.7
    expose:
      - 9200
    ports:
      - "9200:9200"

  kibana:
    image: kibana:6.8.7
    links:
      - "elasticsearch"
    ports:
      - "5601:5601"